server:
  port: 8080
spring:
  application:
    name: "crediya-auth-ms"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: postgres
    schema: public
    username: postgres
    password: mysecretpassword
jwt:
  secret: "your-very-long-secret-key-that-should-be-at-least-256-bits-long-for-security-purposes-and-should-be-stored-securely"
  expiration-ms: 3600000
  refresh-expiration-ms: 86400000
  issuer: "crediya-api"
  json-exp-roles: roles
